### ISSUE TITLE
xelis_wallet does not handle daemon in domain correctly

### ISSUE THREAD

**Issue by Umiiii** [xelis-project/xelis-blockchain#39]
xelis_miner --daemon-address <domain> will always failed 
```bash
Trying to connect to daemon at <domain>
Couldn't connect to daemon: IO error: received corrupt message of type InvalidContentType
```

**Comment by agarwood777** [comment]
Use this to start the miner
xelis_miner.exe   --miner-address xel:xxxxxxxxx  --daemon-address 127.0.0.1:8080

**Comment by Umiiii** [comment]
> Use this to start the miner
> 
> xelis_miner.exe   --miner-address xel:xxxxxxxxx  --daemon-address 127.0.0.1:8080

if you tried to connect domain(i.e. example.com) it will fail since the implementation does not convert the domain to IP address

**Comment by bootesd** [comment]
I keep on getting this error: "Couldn't connect to daemon: IO error: No connection could be made because the target machine actively refused it. (os error 10061)"

I have managed to create a wallet just fine but when I login into it always goes into offline mode because of the above. Also cannot mine as get the same issue. I think I have installed everything correctly. Any idea what I have done wrong?

**Comment by Slixe** [comment]
> I keep on getting this error: "Couldn't connect to daemon: IO error: No connection could be made because the target machine actively refused it. (os error 10061)"

This is mostly because you're not running any local node and the wallet was trying to connect to it.



> xelis_miner --daemon-address will always failed
> 
> ```shell
> Trying to connect to daemon at <domain>
> Couldn't connect to daemon: IO error: received corrupt message of type InvalidContentType
> ```

Can you retry with latest version ?
